name: RELEASE

on:
  pull_request:
    types: [closed]
    branches:
      - "main"

jobs:
  release:
    name: RELEASE
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'release/')
    timeout-minutes: 30
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.17.0

      - name: Get version
        id: get_version
        run: |
          VERSION=`node -p "require('./package.json').version"`
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup de kubectl
        uses: azure/setup-kubectl@v4.0.1
        with:
          version: 'v1.34.4'

      - name: Setup de la configuration de K3s
        env:
          KUBE_CONFIG_B64: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "$KUBE_CONFIG_B64" | base64 -d > /tmp/kubeconfig.yaml

      - name: Fill in the new image ID in the k3s deployment
        run: kubectl --kubeconfig=/tmp/kubeconfig.yaml --insecure-skip-tls-verify set image deployment/${{ secrets.KUBE_DEPLOYMENT }} ${{ secrets.HARBOR_CONTAINER }}=${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/${{ secrets.HARBOR_REPOSITORY }}:${{ steps.get_version.outputs.version }} -n ${{ secrets.KUBE_NAMESPACE }}

      - name: Deploy k3s deployment
        run: kubectl --kubeconfig=/tmp/kubeconfig.yaml --insecure-skip-tls-verify rollout status deployment/${{ secrets.KUBE_DEPLOYMENT }} -n ${{ secrets.KUBE_NAMESPACE }} --timeout=60s

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
        run: |
          gh release create ${{ steps.get_version.outputs.version }} --title "${{ steps.get_version.outputs.version }}" --generate-notes --latest
